import 'dart:convert';import 'package:flutter/material.dart';import 'package:flutter_webrtc/flutter_webrtc.dart';import 'package:permission_handler/permission_handler.dart';import 'package:socket_io_client/socket_io_client.dart' as io;import '../../core/api.dart';import '../../core/config.dart';
class CameraLivePage extends StatefulWidget{final String token;const CameraLivePage({super.key,required this.token});@override State<CameraLivePage> createState()=>_S();}
class _S extends State<CameraLivePage>{final renderer=RTCVideoRenderer();RTCPeerConnection? pc;MediaStream? stream;late io.Socket socket;late Map<String,dynamic> claims;Map<String,dynamic>? _iceConfig;
Map<String,dynamic> decodeClaims(String token)=>jsonDecode(utf8.decode(base64Url.decode(base64Url.normalize(token.split('.').first))));
@override void initState(){super.initState();claims=decodeClaims(widget.token);_initIce();start();}
Future<void> _initIce()async{_iceConfig=await MeshApi().fetchIceConfig(claims['productionId']);}
Future<void> start()async{await [Permission.camera,Permission.microphone].request();await renderer.initialize();stream=await navigator.mediaDevices.getUserMedia({'audio':true,'video':{'facingMode':'environment'}});renderer.srcObject=stream;socket=io.io(AppConfig.apiBaseUrl,io.OptionBuilder().setTransports(['websocket']).setAuth({'token':widget.token}).disableAutoConnect().build());socket.on('director-command',(m){if(m['type']=='REQUEST_OFFER'&&m['cameraId']==claims['participantId'])makeOffer(m['actorId']);});socket.on('signal',(m)=>handleSignal(Map<String,dynamic>.from(m)));socket.connect();setState((){});}
Future<RTCPeerConnection> ensurePeer(String directorId)async{if(pc!=null)return pc!;final config=_iceConfig??AppConfig.defaultIceServers;final p=await createPeerConnection(config);for(final t in stream!.getTracks()){await p.addTrack(t,stream!);}p.onIceCandidate=(c){if(c.candidate!=null)socket.emit('signal',{'productionId':claims['productionId'],'fromParticipantId':claims['participantId'],'toParticipantId':directorId,'type':'ice-candidate','payload':c.toMap()});};pc=p;return p;}
Future<void> makeOffer(String directorId)async{final p=await ensurePeer(directorId);final offer=await p.createOffer();await p.setLocalDescription(offer);socket.emit('signal',{'productionId':claims['productionId'],'fromParticipantId':claims['participantId'],'toParticipantId':directorId,'type':'offer','payload':offer.toMap()});}
Future<void> handleSignal(Map<String,dynamic> m)async{final p=await ensurePeer(m['fromParticipantId']);if(m['type']=='answer'){await p.setRemoteDescription(RTCSessionDescription(m['payload']['sdp'],m['payload']['type']));}else if(m['type']=='ice-candidate'){final x=m['payload'];await p.addCandidate(RTCIceCandidate(x['candidate'],x['sdpMid'],x['sdpMLineIndex']));}}
@override void dispose(){socket.dispose();pc?.close();stream?.dispose();renderer.dispose();super.dispose();}
@override Widget build(BuildContext c)=>Scaffold(backgroundColor:Colors.black,body:Stack(children:[Positioned.fill(child:RTCVideoView(renderer,objectFit:RTCVideoViewObjectFit.RTCVideoViewObjectFitCover)),const SafeArea(child:Padding(padding:EdgeInsets.all(16),child:Chip(label:Text('LIVE CAMERA'))))]));}
