// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1UCyLYyIRT80mjVsOw7hTt54J9yMxvbM',
    appId: '1:524208469179:android:af27927275c73e90ffa59e',
    messagingSenderId: '524208469179',
    projectId: 'yohlab',
    databaseURL: 'https://yohlab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yohlab.firebasestorage.app',
  );
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC1UCyLYyIRT80mjVsOw7hTt54J9yMxvbM',
    appId: '1:524208469179:android:af27927275c73e90ffa59e',
    messagingSenderId: '524208469179',
    projectId: 'yohlab',
    databaseURL: 'https://yohlab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yohlab.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuqWTl0f2XV4I29vqzpK3FCjsdo-qZVeY',
    appId: '1:524208469179:ios:b55bda1bef65a9d0ffa59e',
    messagingSenderId: '524208469179',
    projectId: 'yohlab',
    databaseURL: 'https://yohlab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yohlab.firebasestorage.app',
    androidClientId: '524208469179-3dp2o4c5ksh2hcqt8o8ghhdq7rm19ai1.apps.googleusercontent.com',
    iosClientId: '524208469179-rod29sanjne40ig1h1dqimduh4bh04v6.apps.googleusercontent.com',
    iosBundleId: 'com.yohpal.yohpalLiveV2',
  );
}
