#!/usr/bin/env bash
set -e

if [ ! -f ".env" ]; then
  echo ".env missing. Copy .env.example to .env first."
  exit 1
fi

set -a
source .env
set +a

TURN_PORT="${TURN_PORT:-3478}"
TURN_USERNAME="${TURN_USERNAME:-localuser}"
TURN_PASSWORD="${TURN_PASSWORD:-localpass}"
TURN_REALM="${TURN_REALM:-localhost}"

mkdir -p docker/turn

cat > docker/turn/turnserver.conf <<EOF
# Generated by scripts/generate-turn-config.sh
# Do not edit manually. Edit .env instead.

listening-port=${TURN_PORT}

lt-cred-mech
user=${TURN_USERNAME}:${TURN_PASSWORD}
realm=${TURN_REALM}

fingerprint
no-cli

no-tls
no-dtls

min-port=20000
max-port=20100

verbose
EOF

echo "Generated docker/turn/turnserver.conf"
echo "TURN username: ${TURN_USERNAME}"
echo "TURN realm: ${TURN_REALM}"
